### ISSUE TITLE
No itp output

### ISSUE THREAD

**Issue by WillPPK** [Martini-Force-Field-Initiative/Bartender#9]
Hi all,

The run finished last night and these are my last output.

```
goroutine 1 [running]:
main.FramePar(0xc00035c020, {0x765588, 0xc0000b66c0}, {0xc000015b40, 0x7, 0x416545?}, 0xc0000cb740, {0xb95000, 0x0, 0x0}, ...)
	/wrk/programs/github.com/rmera/bartender-dev_noBeads/geos.go:199 +0x1125
main.TrajAn({0x766548, 0xc00036a030}, {0x765588, 0xc0000b66c0}, {0xc000015b40, 0x7, 0x8}, 0xc0000cb740, 0x1)
	/wrk/programs/github.com/rmera/bartender-dev_noBeads/geos.go:92 +0x5ac
main.main()
	/wrk/programs/github.com/rmera/bartender-dev_noBeads/main.go:243 +0x147a
```
and the file outputs are:

```
1PBC_bartender.inp  Beads.pdb  charges  gochem.inp  gochem.out  gochem.xyz  mdrestart  pbc.pdb*  wbo  xtbmdok  xtbtopo.mol  xtb.trj  xvg/
```

There is no itp so I guess it dies midway. Do you know how I can diagnose why and where and when?

Cheers

Will

**Comment by rmera** [comment]
Hey,

I think the original error is a little further up.  I think with the full error message I might get an idea of what's wrong.

Cheers!

**Comment by rmera** [comment]
Yes!

That could be a bug (Bartender seems to be trying to read something that isn't there), but it could also be an issue of the input file mentioning an atom that doesn't exist in the geometry (say, atom number 12 in a geometry with 10 atoms).

**Comment by rmera** [comment]
I'm closing this due to lack of activity.
